skeleton/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end
  end
  
  resources :users
  resource :session 
  root to: redirect('/cats')
end

skeleton/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint(8)        not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string           not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

require 'action_view'

class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper

  # .freeze renders a constant immutable.
  CAT_COLORS = %w(black white orange brown).freeze

  validates :color, inclusion: CAT_COLORS
  validates :sex, inclusion: %w(M F)
  validates :birth_date, :color, :name, :sex, presence: true
  # validates :user_id, presence: true
  
  # belongs_to :owner, 
  #   foreign_key: :user_id, 
  #   class_name: :User

  # Remember, has_many is just a method where the first argument is
  # the name of the association, and the second argument is an options
  # hash.
  has_many :rental_requests,
    class_name: :CatRentalRequest,
    dependent: :destroy

  def age
    time_ago_in_words(birth_date)
  end
end

skeleton/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.user_id = current_user.id if current_user
    if @cat.save
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :edit
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:age, :birth_date, :color, :description, :name, :sex)
  end
end

skeleton/app/helpers/cats_helper.rb
module CatsHelper
end

skeleton/app/views/cats/_form.html.erb
<% action = (cat.persisted? ? cat_url(cat) : cats_url) %>
<% method = (cat.persisted? ? :patch : :post) %>

<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
  <label for="cat_name">Name</label>
  <input
    type="text"
    name="cat[name]"
    id="cat_name"
    value="<%= cat.name %>">

  <label for="cat_birth_date">Birth date</label>
  <input
    type="date"
    name="cat[birth_date]"
    id="cat_birth_date"
    value="<%= cat.birth_date %>">
  <br>

  <label for="cat_color">Color</label>
  <select name="cat[color]" id="cat_color">
  <option disabled selected>-- select a color --</option>
    <% Cat::CAT_COLORS.each do |color| %>
      <option
        <%= cat.color == color ? "selected" : "" %>
        value="<%= color %>">
        <%= color.upcase %>
      </option>
    <% end %>
  </select>
  <br>

  <input
    type="radio"
    name="cat[sex]"
    value="M"
    id="cat_sex_male"
    <%= cat.sex == "M" ? "checked" : "" %>>
  <label for="cat_sex_male">Male</label>
  <input
    type="radio"
    name="cat[sex]"
    value="F"
    id="cat_sex_female"
    <%= cat.sex == "F" ? "checked" : "" %>>
  <label for="cat_sex_female">Female</label>
  <br>

  <label>
    Description
    <textarea name="cat[description]"><%= cat.description %></textarea>
  </label>

  <% submit_text = (cat.persisted? ? 'Update' : 'Create') + ' cat!' %>
  <input type="submit" value="<%= submit_text %>">
</form>

skeleton/app/views/cats/_req_tr.html.erb
<tr>
  <td><%= req.start_date %></td>
  <td><%= req.end_date %></td>
  <td>
    <% if req.pending? %>
        <form action="<%= approve_cat_rental_request_url(req) %>" method="post">
          <input
            type="hidden"
            name="authenticity_token"
            value="<%= form_authenticity_token %>">
          <input type="submit" value="Approve">
        </form>
        
        <form action="<%= deny_cat_rental_request_url(req) %>" method="post">
          <input
            type="hidden"
            name="authenticity_token"
            value="<%= form_authenticity_token %>">
          <input type="submit" value="Deny">
        </form>
    <% else %>
      <%= req.status %>
    <% end %>
  </td>
</tr>

skeleton/app/views/cats/edit.html.erb
<h1>Edit My Cat</h1>
<%= render 'shared/errors' %>
<%= render 'form', cat: @cat %>

skeleton/app/views/cats/index.html.erb
<h1>Cats upon cats!</h1>

<ul>
  <% @cats.each do |cat| %>
    <li><a href="<%= cat_url(cat) %>"><%= cat.name %></a></li>
  <% end %>
</ul>

<% if !current_user %>
  <h1> Welcome  </h1>
<% end %>
<a href="<%= new_cat_url %>">Create cat</a>

skeleton/app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render 'shared/errors' %>
<%= render 'form', cat: @cat %>

skeleton/app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<table>
  <tr>
    <th>Attribute</th>
    <th>Value</th>
  </tr>
  <% [:age, :birth_date, :color, :sex].each do |attr_name| %>
    <tr>
      <td><%= attr_name %></td>
      <td><%= @cat.send(attr_name) %></td>
    </tr>
  <% end %>
</table>

<a href="<%= edit_cat_url(@cat) %>">Edit <%= @cat.name %></a>

<h2>Rental Requests</h2>
<table>
  <tr>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Status</th>
  </tr>
  <% @cat.rental_requests.order('start_date').each do |req| %>
    <%= render 'req_tr', req: req %>
  <% end %>
</table>